security:
    enable_authenticator_manager: true
    encoders:
        Symfony\Component\Security\Core\User\InMemoryUser:
            algorithm: plaintext

    providers:
        in_memory:
            memory:
                users:
                    mon_user:
                        password: mon_password
                        roles: ['ROLE_USER']

    firewalls:
        login:
            pattern: ^/api/security/generate-token
            stateless: true
            json_login:
                check_path: /api/security/generate-token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        api_doc:
            pattern: ^/api/doc
            security: false

        main:
            pattern: ^/$
            security: false

    access_control:
        - { path: ^/api/genres, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
