controllers:
    resource: ../src/Controller/
    type: annotation

app.swagger:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

api_login_check:
    path: /api/security/generate-token
    options: {expose: true}